using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace BE.Models;
public enum PaymentStatus { Pending, Paid, Failed, Expired }
public class Payment
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int PaymentID { get; set; }
    public int BookingID { get; set; }
    [ForeignKey(nameof(BookingID))]
    public Booking? Booking { get; set; }
    public long Amount { get; set; } // Amount to be paid, in VND
    public PaymentStatus Status { get; set; }
    public string OrderId { get; set; } = ""; // Generated by ME, sent to MoMo, unique per payment attempt
    public string RequestId { get; set; } = ""; // Generated by ME, sent to MoMo, unique per API call — for MoMo's idempotency/dedup
    public string? TransactionId { get; set; } // Generated by MOMO, returned only if payment succeeds — MoMo's own reference number for the completed transaction
    public int? ResultCode { get; set; }
    public string? PayUrl { get; set; }       // url to redirect to MoMo payment page
    public DateTime? ExpiresAt { get; set; }  // MoMo's orderExpireTime
    public DateTime CreatedAt { get; set; }
    public DateTime? PaidAt { get; set; } // Set when IPN confirms payment success

    public ICollection<PaymentGatewayLog> PaymentGatewayLogs { get; set; } = new List<PaymentGatewayLog>();
}