using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace BE.Models;
public enum PaymentAttemptStatus { Init, Redirected, Success, Failed, Expired }
public class PaymentAttempt
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int AttemptID { get; set; }
    public int PaymentID { get; set; }
    [ForeignKey(nameof(PaymentID))]
    public Payment? Payment { get; set; }

    // OrderId: Generated by ME, sent to MoMo, unique per payment attempt
    // format recommended CATCAFE-{paymentId}-{timestamp}
    [Required]
    public string OrderId { get; set; } = "";

    // Generated by ME, sent to MoMo, unique per API call if it's new payment
    // Retry for more clean information will re-use the same requestId
    [Required]
    public string RequestId { get; set; } = "";

    // Generated by MOMO, returned only if payment succeeds
    // MoMo's own reference number for the completed transaction
    public string? TransactionId { get; set; }
    public int? ResultCode { get; set; } 
    public string? PayUrl { get; set; }// url to redirect to MoMo payment page
    public PaymentAttemptStatus Status { get; set; }
    public DateTime? ExpiresAt { get; set; } // MoMo's orderExpireTime
    public DateTime CreatedAt { get; set; }
    public ICollection<PaymentGatewayLog> PaymentGatewayLogs { get; set; } = new List<PaymentGatewayLog>();
}